### ISSUE TITLE
Invalid answers to questions should not trigger default action

### ISSUE THREAD

**Issue by fkusei** [seibert-media/automatix#30]
Log:
```
(19) [python]: wait_url_200('https://some-unreachable-url', timeout=600)
>> my-automatix-script << Command (19) failed with return code 1.
[CF] What should I do? (p: proceed (default), r: retry, a: abort)s
```
I answered `s` here, which is not a supported option in this case. Automatix should notify the user about inputting an invalid option, then re-ask.

**Comment by j-p-a-u-l** [comment]
I would say, thats more a feature request than a bug. `s` is not explicitly listed here but implicit in (default), which means anything else.
But I get your point. Maybe it is more clearly and intuitive, if the default only applies to empty values.
