### ISSUE TITLE
Syntax validation throws false positive

### ISSUE THREAD

**Issue by nkoch-ops** [seibert-media/automatix#32]
If a script uses a function that ends with `_node`, i.e.  `get_all_ips_for_node`, automatix erroneously throws a deprecation warning.

**Comment by j-p-a-u-l** [comment]
Uhh ... Any ideas? Maybe just deprecation warnings for real nodes?

**Comment by nkoch-ops** [comment]
One possibility would be to extend the validation regex to something like this: `r'(\w*)_node(?![\w|(])'`
That should exclude function calls.
